# Based on post at:  https://community.containo.us/t/swarm-mode-giving-404/2746/3
# Contains only additions to the no-https companion docker-compose file

# Enable ACME (Let's Encrypt): automatic SSL.
version: "3.7"

services:
  reverse-proxy:
    ports:
      - "443:443"
    volumes:
      - ./acme:/etc/traefik/acme
    command:
      - --entrypoints.websecure.address=:443
      - --certificatesResolvers.le.acme.email=glycam@gmail.com
      - --certificatesResolvers.le.acme.storage=/etc/traefik/acme/acme.json
      - --certificatesResolvers.le.acme.httpChallenge=true
      - --certificatesResolvers.le.acme.httpChallenge.entryPoint=web
    deploy:
      labels:
        # Global http to https redirect -- Not sure if this is doing anything at all (BLF)
        - --traefik.http.routers.http-catchall.rule="hostregexp(`{host:.+}`)"
        - --traefik.http.routers.http-catchall.entrypoints=web
        - --traefik.http.routers.http-catchall.middlewares=redirect-to-https
        # Middleware redirect -- Not sure if this is doing anything at all (BLF)
        - --traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https


